esphome:
  name: "${devicename}"
  # platform: ESP32
  # board: nodemcu-32s
  comment: "${devicename} heater"
  project:
    name: "nbogojevic.esp32heater"
    version: "1.1"
  on_boot:
    priority: 600 # -100 for modbus, 600 for heat_on_power
    then:
      - script.execute: heat_on_power
      ## configure controller settings at setup
      ## make sure priority is lower than setup_priority of modbus_controller
      # - lambda: |-
      #     auto new_address = 0x01;

      #     if(new_address < 0x01 || new_address > 0xF7) // sanity check
      #     {
      #       ESP_LOGE("ModbusLambda", "Address needs to be between 0x01 and 0xF7");
      #       return;
      #     }

      #     esphome::modbus_controller::ModbusController *controller = id(pzem);
      #     auto set_addr_cmd = esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
      #       controller, 0x0002, new_address);

      #     delay(200) ;
      #     controller->queue_command(set_addr_cmd);
      #   ESP_LOGI("ModbusLambda", "PZEM Addr set");

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:
  level: "${log_level}"
  logs:
    sensor: INFO

# Enable Home Assistant API
api:

safe_mode:
  num_attempts: 100
  reboot_timeout: 15min

# Enable OTA
ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"

switch:
  # Solid-state switch pin
  - platform: gpio
    pin:
      number: ${solid_state_pin}
    id: heater_switch
    restore_mode: ALWAYS_OFF
    name: "${devicename} Heater"
  - platform: restart
    name: "${devicename} Restart"
    id: reboot
    disabled_by_default: true

spi:
  miso_pin: ${miso_pin}
  clk_pin: ${clk_pin}

uart:
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false

modbus:
  send_wait_time: 200ms
  id: mod_bus_pzem

# modbus_controller:
#   - id: pzem
#     # The current device address.
#     # address: 0x1
#     # The special address 0xF8 is a broadcast address accepted by any pzem device,
#     # so if you use this address, make sure there is only one pzem device connected
#     # to the uart bus.
#     address: 0xF8
#     modbus_id: mod_bus_pzem
#     command_throttle: 0ms
#     setup_priority: -10
#     update_interval: 30s
#     on_online:
#       then:
#         - logger.log: "Controller back online!"

binary_sensor:
  # Up
  - platform: template
    name: "${devicename} Safety Stop"
    id: safety_stop
    device_class: problem

sensor:
  # Digital temperature sensor
  - platform: dht
    pin: ${dht_pin}
    temperature:
      name: "${devicename} DHT Temperature"
      id: dht_temperature
      icon: "mdi:thermometer-chevron-up"
      accuracy_decimals: 0
      on_value:
        - if:
            condition:
              and:
                - lambda: return x >= ${overheat_stop_above};
                - switch.is_on: heater_switch
            then:
              - logger.log: "!! DHT too hot !!"
              - switch.turn_off: heater_switch
              - binary_sensor.template.publish:
                  id: safety_stop
                  state: ON
            else:
              - if:
                  condition:
                    and:
                      - lambda: |-
                          return x <= ${overheat_start_below}
                            && id(heater).mode == climate::CLIMATE_MODE_HEAT
                            && id(heater).action == climate::CLIMATE_ACTION_HEATING;
                      - switch.is_off: heater_switch
                  then:
                    - logger.log: "DHT cooled down"
                    - switch.turn_on: heater_switch
                    - binary_sensor.template.publish:
                        id: safety_stop
                        state: OFF

    humidity:
      name: "${devicename} DHT Humidity"
      id: dht_humidity
    update_interval: 30s
  - platform: max6675
    id: thermocouple_temperature
    name: "${devicename} Thermocouple Temperature"
    cs_pin: ${cs_pin}
    update_interval: 10s
  - platform: pzemac
    current:
      name: "${devicename} Current"
    voltage:
      name: "${devicename} Voltage"
    energy:
      name: "${devicename} Energy"
    power:
      name: "${devicename} Power"
    frequency:
      name: "${devicename} Frequency"
    power_factor:
      name: "${devicename} Power Factor"
    update_interval: 10s
  - platform: template
    name: "${devicename} Ambient Temperature"
    id: ambient_temperature
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    accuracy_decimals: 0
    lambda: |-
      // Check if it is not overheating
      auto source = id(temperature_source).current_option();
      if (source == "Home Assistant") {
        if (id(homeassistant_temperature).has_state() && id(homeassistant_temperature).state != NAN && id(homeassistant_temperature).state < 50) {
          id(source_state).publish_state("OK");
          return floor(id(homeassistant_temperature).state);
        }
      }
      if (source == "DHT" && id(dht_temperature).has_state()) {
        id(source_state).publish_state("OK");
        return floor(id(dht_temperature).state);
      }
      if (source == "Thermocouple" &&id(thermocouple_temperature).has_state()) {
        id(source_state).publish_state("OK");
        return floor(id(thermocouple_temperature).state);
      }
      // Fallback
      if (id(dht_temperature).has_state()) {
        id(source_state).publish_state("DHT Source");
        return floor(id(dht_temperature).state);
      }
      id(source_state).publish_state("Source Error");
      return {};
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    entity_id: ${homeassistant_sensor}
    id: homeassistant_temperature
  - platform: internal_temperature
    name: "${devicename} Internal Temperature"
    id: internal_chip_temperature
    # on_value:
    #   - if:
    #       condition:
    #         and:
    #           - lambda: return x >= MAX_INTERNAL_TEMPERATURE;
    #           - switch.is_on: heater_switch
    #       then:
    #         - logger.log: "!! ESP32 too hot !!"
    #         - switch.turn_off: heater_switch
    #         - binary_sensor.template.publish:
    #             id: safety_stop
    #             state: ON
    #       else:
    #         - if:
    #             condition:
    #               and:
    #                 - lambda: |-
    #                     return x <= INTERNAL_TEMPERATURE_RESUME
    #                       && id(heater).mode == climate::CLIMATE_MODE_HEAT
    #                       && id(heater).action == climate::CLIMATE_ACTION_HEATING;
    #                 - switch.is_off: heater_switch
    #             then:
    #               - logger.log: "DHT cooled down"
    #               - switch.turn_on: heater_switch
    #               - binary_sensor.template.publish:
    #                   id: safety_stop
    #                   state: OFF

select:
  - platform: template
    name: "${devicename} Temperature Source"
    id: temperature_source
    optimistic: true
    icon: "mdi:eye"
    options:
      - DHT
      - Home Assistant
      - Thermocouple
    initial_option: ${initial_source}
    restore_value: true

# Information sensors
text_sensor:
  - platform: template
    name: "${devicename} Source State"
    id: source_state
    icon: "mdi:information-outline"

climate:
  - platform: thermostat
    name: "${devicename} Heating"
    id: heater
    sensor: ambient_temperature
    default_preset: Home
    on_boot_restore_from: memory
    min_heating_off_time: 30s
    min_heating_run_time: 10s
    set_point_minimum_differential: 1 °C
    min_idle_time: 10s
    heat_action:
      - switch.turn_on: heater_switch
      - binary_sensor.template.publish:
          id: safety_stop
          state: OFF
    idle_action:
      - switch.turn_off: heater_switch
      - binary_sensor.template.publish:
          id: safety_stop
          state: OFF
    preset:
      - name: Home
        mode: heat
        default_target_temperature_low: ${default_target_temperature}

script:

  - id: heat_on_power
    then:
      - delay: 1min
      - logger.log: "Initial setup"
      - if:
          condition:
            time.has_time:
          then:
            - if:
                condition:
                  - lambda: |-
                      auto month = id(homeassistant_time).now().month;
                      return month >= 10 || month <= 4;
                then:
                  - logger.log: "HEAT on boot in cold season"
                  - climate.control:
                      id: heater
                      mode: "HEAT"
                else:
                  - logger.log: "OFF on boot in warm season"
                  - climate.control:
                      id: heater
                      mode: "OFF"
          else:
            - logger.log: "HEAT on boot by default"
            - climate.control:
                id: heater
                mode: HEAT
